kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-volumeclaim
  annotations:
    value: 'wow'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 360Gi